# Generated by Django 5.0.6 on 2024-07-03 18:58

import account.models
import django.db.models.deletion
import djangoyearlessdate.models
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Personal", max_length=50)),
                ("headline", models.CharField(blank=True, max_length=120, null=True)),
                ("location", models.CharField(blank=True, max_length=80, null=True)),
                ("description", models.CharField(blank=True, null=True)),
                (
                    "connections",
                    models.ManyToManyField(
                        through="account.Connection", to="account.profile"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="connection",
            name="profile_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_from_set",
                to="account.profile",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="profile_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_to_set",
                to="account.profile",
            ),
        ),
        migrations.CreateModel(
            name="Vcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("group", "Group"),
                            ("org", "Organization"),
                            ("location", "Location"),
                        ],
                        default="individual",
                        max_length=15,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to=account.models.vcard_img_dir_path
                    ),
                ),
                (
                    "birthday",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "birthday_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "anniversary",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "anniversary_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("N", "Not Applicable"),
                            ("U", "Unknown"),
                        ],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("note", models.CharField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "url_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=5,
                        null=True,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=30)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="vcard",
            field=models.OneToOneField(
                limit_choices_to={
                    "user": models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="account.vcard",
            ),
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CELL", "Cell"),
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("VOICE", "Voice"),
                            ("TEXT", "Text"),
                            ("FAX", "Fax"),
                            ("PAGER", "Pager"),
                            ("other", "Other"),
                        ],
                        default="CELL",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("role", models.CharField(max_length=250)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=account.models.vcard_img_dir_path,
                    ),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=5,
                        null=True,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="connection",
            name="vcard",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.vcard",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("other", "Other"),
                        ],
                        default="WORK",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("street1", models.CharField()),
                ("street2", models.CharField(blank=True, null=True)),
                ("city", models.CharField()),
                ("state", models.CharField()),
                ("zip", models.CharField(max_length=10)),
                ("country", models.CharField(blank=True, null=True)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["-created"], name="account_con_created_154e4e_idx"
            ),
        ),
    ]
