# Generated by Django 5.0.6 on 2024-06-28 19:26

import account.models
import django.db.models.deletion
import djangoyearlessdate.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=120, null=True)),
                ("location", models.CharField(blank=True, max_length=80, null=True)),
                ("description", models.CharField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("group", "Group"),
                            ("org", "Organization"),
                            ("location", "Location"),
                        ],
                        default="individual",
                        max_length=15,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to=account.models.vcard_img_dir_path
                    ),
                ),
                (
                    "birthday",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "birthday_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "anniversary",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "anniversary_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("N", "Not Applicable"),
                            ("U", "Unknown"),
                        ],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("note", models.CharField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "url_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=5,
                        null=True,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=30)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CELL", "Cell"),
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("VOICE", "Voice"),
                            ("TEXT", "Text"),
                            ("FAX", "Fax"),
                            ("PAGER", "Pager"),
                            ("other", "Other"),
                        ],
                        default="CELL",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("role", models.CharField(max_length=250)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=account.models.vcard_img_dir_path,
                    ),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=5,
                        null=True,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.profile",
                    ),
                ),
                (
                    "vcard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORK", "Work"),
                            ("HOME", "Home"),
                            ("other", "Other"),
                        ],
                        default="WORK",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("street1", models.CharField()),
                ("street2", models.CharField(blank=True, null=True)),
                ("city", models.CharField()),
                ("state", models.CharField()),
                ("zip", models.CharField(max_length=10)),
                ("country", models.CharField(blank=True, null=True)),
                (
                    "vcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vcard"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="ContactNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="account_con_created_1e4e16_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["-created"], name="account_con_created_8bdae6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("user", "profile"),
                name="unique_user_connection",
                nulls_distinct=True,
            ),
        ),
    ]
