# Generated by Django 5.0.6 on 2024-07-08 15:45

import django.db.models.deletion
import djangoyearlessdate.models
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseOrgProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prop_type",
                    models.CharField(
                        choices=[("t", "TITLE"), ("r", "ROLE"), ("o", "ORG")],
                        max_length=1,
                    ),
                ),
                ("value", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Org",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.baseorgproperty",),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.baseorgproperty",),
        ),
        migrations.CreateModel(
            name="Title",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.baseorgproperty",),
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("i", "Individual"),
                            ("g", "Group"),
                            ("o", "Organization"),
                            ("l", "Location"),
                        ],
                        default="i",
                        max_length=1,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50)),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="users/profile/photo"),
                ),
                (
                    "birthday",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "birthday_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "anniversary",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "anniversary_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m", "Male"),
                            ("f", "Female"),
                            ("o", "Other"),
                            ("n", "Not Applicable"),
                            ("u", "Unknown"),
                        ],
                        default=None,
                        max_length=1,
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("note", models.CharField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="baseorgproperty",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.card"
            ),
        ),
        migrations.CreateModel(
            name="BaseContentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("param_type", models.CharField(blank=True, max_length=100)),
                ("group", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("pref", models.BooleanField(default=False)),
                ("other_params", models.CharField(blank=True, max_length=50)),
                ("value", models.CharField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.card"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        blank=True,
                        choices=[("w", "Work"), ("h", "Home"), ("o", "Other")],
                        default="w",
                        max_length=1,
                    ),
                ),
                ("street1", models.CharField()),
                ("street2", models.CharField(blank=True)),
                ("city", models.CharField()),
                ("state", models.CharField()),
                ("zip", models.CharField(max_length=10)),
                ("country", models.CharField(blank=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.card"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.card",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True,
                        choices=[("w", "Work"), ("h", "Home"), ("o", "Other")],
                        default=None,
                        max_length=1,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.card"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("c", "Cell"),
                            ("w", "Work"),
                            ("h", "Home"),
                            ("v", "Voice"),
                            ("t", "Text"),
                            ("f", "Fax"),
                            ("p", "Pager"),
                            ("o", "Other"),
                        ],
                        default="c",
                        max_length=1,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.card"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Personal", max_length=50)),
                ("headline", models.CharField(blank=True, max_length=120, null=True)),
                ("location", models.CharField(blank=True, max_length=80, null=True)),
                ("description", models.CharField(blank=True, null=True)),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="account.card"
                    ),
                ),
                (
                    "connections",
                    models.ManyToManyField(
                        through="account.Connection", to="account.profile"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="connection",
            name="profile_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_from_set",
                to="account.profile",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="profile_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_to_set",
                to="account.profile",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=30)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.card"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "url_type",
                    models.CharField(
                        blank=True,
                        choices=[("w", "Work"), ("h", "Home"), ("o", "Other")],
                        default=None,
                        max_length=1,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.card"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["-created"], name="account_con_created_154e4e_idx"
            ),
        ),
    ]
