# Generated by Django 5.0.6 on 2024-07-01 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Connection",
        ),
        migrations.RenameField(
            model_name="contactnote",
            old_name="contact",
            new_name="connection",
        ),
        migrations.RenameIndex(
            model_name="connection",
            new_name="account_con_created_154e4e_idx",
            old_name="account_con_created_8bdae6_idx",
        ),
    ]
