# Generated by Django 5.0.6 on 2024-07-01 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_contact_connection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactnote",
            name="connection",
        ),
        migrations.DeleteModel(
            name="Connection",
        ),
        migrations.DeleteModel(
            name="ContactNote",
        ),
    ]
