# Generated by Django 5.0.6 on 2024-07-09 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_delete_org_delete_role_delete_title_org_role_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="org",
            old_name="value",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="value",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="title",
            old_name="value",
            new_name="title",
        ),
    ]
