# Generated by Django 5.0.6 on 2024-07-11 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0004_rename_value_org_organization_rename_value_role_role_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="share_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
