# Generated by Django 5.0.6 on 2024-06-05 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_profile_location_alter_profile_photo_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailaddress",
            options={"verbose_name_plural": "Email Addresses"},
        ),
    ]
