# Generated by Django 5.0.6 on 2024-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_profile_home_page_socialprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="date_of_birth",
            new_name="birthday",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="company",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="job_title",
            new_name="role",
        ),
        migrations.AddField(
            model_name="emailaddress",
            name="email_type",
            field=models.CharField(
                choices=[("WORK", "Work"), ("HOME", "Home"), ("other", "Other")],
                default="WORK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="address_type",
            field=models.CharField(
                choices=[("WORK", "Work"), ("HOME", "Home"), ("other", "Other")],
                default="WORK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="nick_name",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="prefix",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="suffix",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="phone",
            name="phone_type",
            field=models.CharField(
                choices=[
                    ("CELL", "Cell"),
                    ("WORK VOICE", "Work"),
                    ("HOME VOICE", "Home"),
                    ("WORK FAX", "Work Fax"),
                    ("HOME FAX", "Home Fax"),
                    ("PAGER", "Pager"),
                    ("other", "Other"),
                ],
                default="CELL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="home_page",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
