# Generated by Django 5.0.6 on 2024-06-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_rename_date_of_birth_profile_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="anniversary",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Femail"),
                    ("O", "Other"),
                    ("N", "Not Applicable"),
                    ("U", "Unknown"),
                ],
                default=None,
                max_length=20,
                null=True
            ),
        ),
    ]
