# Generated by Django 5.0.6 on 2024-06-25 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_profile_anniversary_profile_gender_profile_sex"),
        ("auth", "0015_alter_user_connections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Connection",
        ),
        migrations.RenameIndex(
            model_name="connection",
            new_name="account_con_created_154e4e_idx",
            old_name="account_con_created_8bdae6_idx",
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("N", "Not Applicable"),
                    ("U", "Unknown"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
