# Generated by Django 5.0.6 on 2024-06-25 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_rename_contact_connection_and_more"),
        ("auth", "0016_remove_user_connections"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Connection",
        ),
    ]
