# Generated by Django 5.0.6 on 2024-10-14 15:37

import django.db.models.deletion
import phonenumber_field.modelfields
import profile.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Website", unique=True, verbose_name="title"
                    ),
                ),
                ("netloc", models.CharField(blank=True, verbose_name="netloc")),
            ],
            options={
                "verbose_name": "linkbase",
                "verbose_name_plural": "linkbases",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "info_type",
                    models.CharField(
                        blank=True,
                        choices=[("W", "Work"), ("H", "Home"), ("O", "Other")],
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
                ("street1", models.CharField(verbose_name="street")),
                ("street2", models.CharField(blank=True, verbose_name="street line 2")),
                ("city", models.CharField(verbose_name="city")),
                ("state", models.CharField(verbose_name="state")),
                ("zip", models.CharField(max_length=10, verbose_name="zip code")),
                ("country", models.CharField(blank=True, verbose_name="country")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[("D", "Document"), ("I", "Image")],
                        max_length=1,
                        verbose_name="attachment type",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="url")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="users/models/attachment",
                        verbose_name="file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                ("end_date", models.DateField(blank=True, verbose_name="end date")),
                (
                    "current",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="current"
                    ),
                ),
                (
                    "degree_type",
                    models.CharField(
                        blank=True,
                        help_text="Associate, bachelor's, master's, etc.",
                        max_length=200,
                        verbose_name="degree type",
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(
                        blank=True,
                        help_text="Grade point average",
                        null=True,
                        verbose_name="GPA",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "info_type",
                    models.CharField(
                        blank=True,
                        choices=[("W", "Work"), ("H", "Home"), ("O", "Other")],
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="email"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "email",
                "verbose_name_plural": "emails",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=200, verbose_name="url")),
                (
                    "is_independent_url",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates url does not require model_type.netlock as the prefix",
                        verbose_name="independent url",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="links",
                        related_query_name="link",
                        to="profile.linkbase",
                        verbose_name="linkbase",
                    ),
                ),
            ],
            options={
                "verbose_name": "link",
                "verbose_name_plural": "links",
                "ordering": ["model_type"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                ("end_date", models.DateField(blank=True, verbose_name="end date")),
                (
                    "current",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="current"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "contributors",
                    models.CharField(
                        blank=True,
                        help_text="Contributors or co-authors",
                        max_length=200,
                        verbose_name="contributors",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Publication, journal, publisher, etc.",
                        max_length=200,
                        verbose_name="project source",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="patent number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Pending"), ("g", "Granted"), ("e", "Expired")],
                    ),
                ),
                (
                    "filing_date",
                    models.DateField(blank=True, verbose_name="filing date"),
                ),
                (
                    "classifications",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="classifications"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country or region",
                        max_length=200,
                        verbose_name="country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "info_type",
                    models.CharField(
                        blank=True,
                        choices=[("W", "Work"), ("H", "Home"), ("O", "Other")],
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="phone number"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "phone",
                "verbose_name_plural": "phones",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("ID", "Individual")],
                        default="ID",
                        max_length=2,
                        verbose_name="kind",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="kind")),
                (
                    "description",
                    models.CharField(blank=True, verbose_name="description"),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, max_length=50, verbose_name="prefix"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="first name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="middle name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="last name"
                    ),
                ),
                (
                    "suffix",
                    models.CharField(blank=True, max_length=50, verbose_name="suffix"),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="nickname"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="users/profile/photo",
                        verbose_name="photo",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="headline"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="location"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="about")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("order", profile.fields.OrderField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": (
                                "email",
                                "phone",
                                "address",
                                "link",
                                "attachment",
                                "award",
                                "certificate",
                                "license",
                                "membership",
                                "workexperience",
                                "volunteerwork",
                                "education",
                                "project",
                                "publishedwork",
                                "patent",
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        related_query_name="content",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "content",
                "verbose_name_plural": "contents",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "contributors",
                    models.CharField(
                        blank=True,
                        help_text="Contributors or co-authors",
                        max_length=200,
                        verbose_name="contributors",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Publication, journal, publisher, etc.",
                        max_length=200,
                        verbose_name="project source",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublishedWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "contributors",
                    models.CharField(
                        blank=True,
                        help_text="Contributors or co-authors",
                        max_length=200,
                        verbose_name="contributors",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Publication, journal, publisher, etc.",
                        max_length=200,
                        verbose_name="project source",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "published work",
                "verbose_name_plural": "published works",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "contributors",
                    models.CharField(
                        blank=True,
                        help_text="Contributors or co-authors",
                        max_length=200,
                        verbose_name="contributors",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Publication, journal, publisher, etc.",
                        max_length=200,
                        verbose_name="project source",
                    ),
                ),
                (
                    "affiliated_institutions",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="affiliated institutions",
                    ),
                ),
                (
                    "funding_source",
                    models.CharField(
                        blank=True,
                        help_text="Grant, institution, etc.",
                        max_length=200,
                        verbose_name="funding source",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "research project",
                "verbose_name_plural": "research projects",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VolunteerWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                ("end_date", models.DateField(blank=True, verbose_name="end date")),
                (
                    "current",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="current"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="label"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("date", models.DateField(blank=True, verbose_name="date")),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="external link"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                ("end_date", models.DateField(blank=True, verbose_name="end date")),
                (
                    "current",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="current"
                    ),
                ),
                (
                    "work_setting",
                    models.CharField(
                        blank=True,
                        choices=[("i", "In-Person"), ("h", "Hybrid"), ("r", "Remote")],
                        max_length=1,
                        verbose_name="work setting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "work experience",
                "verbose_name_plural": "work experiences",
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
    ]
