# Generated by Django 5.0.6 on 2024-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Male"),
                    ("f", "Female"),
                    ("o", "Other"),
                    ("n", "Not Applicable"),
                    ("u", "Unknown"),
                ],
                default="",
                max_length=1,
            ),
        ),
    ]
