# Generated by Django 5.0.6 on 2024-09-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="slug",
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
