# Generated by Django 5.0.6 on 2024-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[("f", "Full-time"), ("p", "Part-time")],
                max_length=1,
                verbose_name="employment type",
            ),
        ),
    ]
