# Generated by Django 5.0.6 on 2024-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profile.attachment",),
        ),
        migrations.CreateModel(
            name="GitHub",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profile.link",),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profile.attachment",),
        ),
        migrations.CreateModel(
            name="Website",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profile.link",),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="model_type",
            field=models.CharField(
                choices=[("d", "Document"), ("i", "Image")],
                max_length=1,
                verbose_name="attachment type",
            ),
        ),
    ]
