# Generated by Django 5.0.6 on 2024-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default="profile", max_length=100),
            preserve_default=False,
        ),
    ]
