# Generated by Django 5.0.6 on 2024-10-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_document_github_image_website_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="award",
            name="title",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="title",
        ),
        migrations.RemoveField(
            model_name="education",
            name="title",
        ),
        migrations.RemoveField(
            model_name="license",
            name="title",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="title",
        ),
        migrations.RemoveField(
            model_name="patent",
            name="title",
        ),
        migrations.RemoveField(
            model_name="project",
            name="title",
        ),
        migrations.RemoveField(
            model_name="publishedwork",
            name="title",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="title",
        ),
        migrations.RemoveField(
            model_name="volunteerwork",
            name="title",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="title",
        ),
        migrations.AlterField(
            model_name="award",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="education",
            name="date",
            field=models.DateField(blank=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="education",
            name="label",
            field=models.CharField(max_length=200, verbose_name="major"),
        ),
        migrations.AlterField(
            model_name="education",
            name="organization",
            field=models.CharField(
                help_text="School, university, etc.",
                max_length=200,
                verbose_name="school",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="date",
            field=models.DateField(blank=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="organization",
            field=models.CharField(max_length=200, verbose_name="organization"),
        ),
        migrations.AlterField(
            model_name="patent",
            name="contributors",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="inventors"
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="date",
            field=models.DateField(
                blank=True, help_text="Issue / Grant date", verbose_name="issue date"
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="patent",
            name="source",
            field=models.CharField(blank=True, max_length=200, verbose_name="assignee"),
        ),
        migrations.AlterField(
            model_name="project",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="publishedwork",
            name="contributors",
            field=models.CharField(max_length=200, verbose_name="authors"),
        ),
        migrations.AlterField(
            model_name="publishedwork",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="publishedwork",
            name="source",
            field=models.CharField(max_length=200, verbose_name="publication source"),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="contributors",
            field=models.CharField(max_length=200, verbose_name="authors"),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="volunteerwork",
            name="date",
            field=models.DateField(blank=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="volunteerwork",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="date",
            field=models.DateField(verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="label",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="organization",
            field=models.CharField(max_length=200, verbose_name="company"),
        ),
    ]
