# Generated by Django 5.0.6 on 2024-11-25 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile', '0003_alter_github_options_alter_content_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('email', 'phone', 'address', 'link', 'attachment', 'award', 'certificate', 'license', 'membership', 'workexperience', 'volunteerwork', 'education', 'project', 'researchproject', 'publishedwork', 'patent', 'skill', 'interest', 'cause')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contentcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('email', 'phone', 'address', 'link', 'attachment', 'award', 'certificate', 'license', 'membership', 'workexperience', 'volunteerwork', 'education', 'project', 'researchproject', 'publishedwork', 'patent', 'skill', 'interest', 'cause')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
