# Generated by Django 5.0.6 on 2024-09-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0003_alter_content_content_type_delete_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Website")),
                ("domain", models.CharField(blank=True)),
                ("svg_id", models.CharField(default="web")),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=200)),
                (
                    "is_independent_url",
                    models.BooleanField(
                        editable=False,
                        help_text="Indicates url does not require linkbase.domain as the prefix",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linkbase",
                    models.ForeignKey(
                        default=0,
                        editable=False,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="profile.linkbase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
