# Generated by Django 5.0.6 on 2024-10-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0003_remove_award_title_remove_certificate_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="education",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="license",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="patent",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Issue / Grant date",
                null=True,
                verbose_name="issue date",
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="filing_date",
            field=models.DateField(blank=True, null=True, verbose_name="filing date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="publishedwork",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="volunteerwork",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="volunteerwork",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
    ]
