# Generated by Django 5.0.6 on 2024-09-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0004_linkbase_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="is_independent_url",
            field=models.BooleanField(
                help_text="Indicates url does not require linkbase.domain as the prefix"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="linkbase",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="profile.linkbase",
            ),
        ),
    ]
