# Generated by Django 5.0.6 on 2024-10-17 18:41

import django.db.models.deletion
import profile.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("profile", "0004_alter_award_date_alter_certificate_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("order", profile.fields.OrderField(blank=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontents",
                        related_query_name="contentcontent",
                        to="profile.content",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": (
                                "email",
                                "phone",
                                "address",
                                "link",
                                "attachment",
                                "award",
                                "certificate",
                                "license",
                                "membership",
                                "workexperience",
                                "volunteerwork",
                                "education",
                                "project",
                                "publishedwork",
                                "patent",
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
