# Generated by Django 5.0.6 on 2024-12-12 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_content_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200)),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('o', 'Outstanding'), ('a', 'Accepted'), ('d', 'Declined')], default='o', max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from_set', to='profile.profile')),
                ('profile_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_set', to='profile.profile')),
            ],
            options={
                'ordering': ('-requested',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='requests_made',
            field=models.ManyToManyField(related_name='requests_of', through='profile.ConnectionRequest', to='profile.profile'),
        ),
    ]
