# Generated by Django 5.0.6 on 2024-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_connectionrequest_profile_requests_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelink',
            name='is_expired',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
    ]
