# Generated by Django 5.0.6 on 2024-10-17 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0005_contentcontent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentcontent",
            options={"ordering": ["order"]},
        ),
    ]
