# Generated by Django 5.0.6 on 2024-12-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_profilelink_is_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilelink',
            options={'ordering': ['-created'], 'verbose_name': 'profile link', 'verbose_name_plural': 'profile links'},
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', related_query_name='link', to='profile.profile'),
        ),
    ]
