# Generated by Django 5.0.6 on 2024-10-18 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0006_alter_contentcontent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileLink",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires", models.DateTimeField(null=True)),
                ("last_viewed", models.DateTimeField(auto_now=True)),
                ("max_views", models.IntegerField(null=True)),
                ("views", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        related_query_name="profile",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile link",
                "verbose_name_plural": "profile links",
            },
        ),
    ]
