# Generated by Django 5.0.6 on 2024-10-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("profile", "0007_alter_content_content_type_attachment_delete_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="media_type",
            new_name="attachment_type",
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": ("email", "phone", "address", "link", "attachment")
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
