# Generated by Django 5.0.6 on 2024-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0007_profilelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilelink",
            name="label",
            field=models.CharField(
                default="asdf", max_length=200, verbose_name="label"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profilelink",
            name="expires",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="profilelink",
            name="max_views",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="maximum number of views"
            ),
        ),
    ]
