# Generated by Django 5.0.6 on 2024-10-10 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("profile", "0008_rename_media_type_attachment_attachment_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(blank=True, upload_to="users/models/attachment"),
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": (
                        "email",
                        "phone",
                        "address",
                        "link",
                        "attachment",
                        "award",
                        "certificate",
                        "license",
                        "membership",
                        "workexperience",
                        "volunteerwork",
                        "education",
                        "project",
                        "publishedwork",
                        "patent",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "degree_type",
                    models.CharField(
                        blank=True,
                        help_text="Associate, bachelor's, master's, etc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("gpa", models.FloatField(blank=True, help_text="GPA", null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "contributors",
                    models.CharField(
                        blank=True,
                        help_text="Contributors or co-authors",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Publication, journal, publisher, etc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, help_text="Patent No.", max_length=200, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Pending"), ("g", "Granted"), ("e", "Expired")],
                    ),
                ),
                (
                    "filing_date",
                    models.DateField(blank=True, help_text="Filing date", null=True),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        help_text="Classifications",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country or region",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "contributors",
                    models.CharField(
                        blank=True,
                        help_text="Contributors or co-authors",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Publication, journal, publisher, etc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublishedWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "contributors",
                    models.CharField(
                        blank=True,
                        help_text="Contributors or co-authors",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Publication, journal, publisher, etc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VolunteerWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
                ("date", models.DateField(blank=True, help_text="Date", null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "work_setting",
                    models.CharField(
                        blank=True,
                        choices=[("i", "In-person"), ("h", "Hybrid"), ("r", "Remote")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-date"],
                "abstract": False,
            },
        ),
    ]
